Updated operators to print with hat
QuantumSavory/QuantumSymbolics.jl pull request #79
Opened 2024-08-13 14:44 UTC by rbaliarizona

Operators now print with hat on top

2024-08-13 14:45 UTC, rbaliarizona commented
@Krastanov  my main goal here was to familiarize myself with the pull-request process. I personally like my operators to display with hats, but I know this isn't a law, so feel free to discard this change. Any feedback on if I went through the pull request process would be welcome though :)

2024-08-13 15:04 UTC, Krastanov commented
This is great, Rohan, thanks! I will run a review on it later today

2024-08-13 15:08 UTC, Krastanov requested changes
I love that the PR is small -- way easier to review and merge.

I left one inline comment on some code details.

There are a lot of failing tests. An easy way to run the tests locally and check things is to do `] test QuantumSymbolics` -- that way you can find exactly which test is failing and focus on it.

Most of the tests here seem to be "doctests" that just lack a hat. There is an automated way to fix them (the `fix` argument to `doctest` function).

Happy to discuss testing more at the hackathon.

2024-08-13 15:08 UTC, Krastanov commented on src/QSymbolicsBase/literal_objects.jl
> +Base.show(io::IO, x::Union{SOperator,SHermitianOperator,SUnitaryOperator,SHermitianUnitaryOperator,SSuperOperator}) = print(io, "$(symbollabel(x))̂")
Two points:

- we probably should insert the hat on the first letter (not all operators are a single symbol)

- let's remove `SSuperOperator` from this list for the moment, as it has a bit more complicated printing

2024-08-14 00:36 UTC, rbaliarizona commented
@Krastanov thanks for the feedback!

I have updated the doctests. Hopefully they pass now. 

I actually added logic to make the hat print on the middle character instead. I know this wasn't your suggestion and it may be more logic that we are looking for here. Lmk what you think!

2024-11-14 21:11 UTC, Krastanov commented
apologies, it seems I messed up the merge with master. Let me try to fix that

2024-11-14 21:54 UTC, Krastanov commented
Darn, there are a few new places in the documentation where the hats need to be added. For now I will mark this as a draft as I will not have the time to make these changes. Apologies for the delay. Happy to pick it back up if you are interested in finishing it, but no pressure on that.

2024-11-14 22:27 UTC, rbaliarizona commented
Hi @Krastanov , thanks for looking at it. Unfortunately I think I will need to drop this, atleast for now.

2024-11-15 06:26 UTC, Krastanov commented
no worries!

2024-11-15 06:26 UTC, closed without merging