Migrate `express` functionality and `AbstractRepresentation` type to QuantumInterface
QuantumSavory/QuantumSymbolics.jl pull request #93
Opened 2024-12-22 09:28 UTC by apkille

#92 https://github.com/qojulia/QuantumInterface.jl/pull/46
The problem with this PR and the one in QuantumInterface is that a type piracy is introduced here:
```
express(s, repr::AbstractRepresentation) = express(s, repr, UseAsState())
```
I suppose we could migrate `AbstractUse` and its subtypes to QuantumInterface as well, but 
```
function express(state::Symbolic, repr::AbstractRepresentation, use::AbstractUse)
```
would then be a type piracy. Plus `AbstractUse` is intended for dealing with edge cases in symbolic-to-Clifford translations, so to me it doesn't make sense to migrate it up to QuantumInterface.

2024-12-30 18:26 UTC, apkille commented
@Krastanov

2025-01-16 16:49 UTC, Krastanov requested changes
Looks good! Three minor things:

- The comment about `AbstractUse` -- I think it makes sense to move this too. E.g. if QuantumClifford is converting an Operator it needs to know whether the user wants a Stabilizer or a CliffordOperator
- The docstring update (or move)
- Check that `express` still shows in the documentation -- now that it does not belong to QuantumSymbolics, it might need to be explicitly included.

Otherwise feel free to merge once CI passes, the Project.toml is bumped, without waiting for another review. I guess that requires the other PR in QuantumInterface to be merged first.

2025-01-16 16:49 UTC, Krastanov commented on src/QSymbolicsBase/QSymbolicsBase.jl
>  struct UseAsOperation <: AbstractUse end
Let's move these too, unless there is a reason not to.

2025-01-16 16:49 UTC, Krastanov commented on src/QSymbolicsBase/express.jl
> -function express end
Could you update the docstring above, so it is clear this is about symbolics, not about all of the express capabilities? Just adding the work "symbolic" somewhere would be enough.

2025-01-16 16:58 UTC, Krastanov commented
Marking it as a draft to remove it from my review queue for now. Convert it back when ready and merge (or ping me to merge).

2025-01-18 16:59 UTC, merged

2025-01-18 17:00 UTC, apkille commented
> * Check that `express` still shows in the documentation -- now that it does not belong to QuantumSymbolics, it might need to be explicitly included.
 
It still shows in the docs.